trim/config/routes.rb
Rails.application.routes.draw do
  resources :users

  get "/welcome" => "users#index"
  get "/apprentice" => "users#new"

  root to: "users#index"

end

trim/app/models/user.rb
class User < ActiveRecord::Base
  validates :fullname, :email, :repo, :url, presence: true, length: { maximum: 200 }
  validates :email, uniqueness: true
  validates :oop, :modular, :workflow, :testing, :database, :problem, :javascript,
            :html, :css, :team, :selfmotivate, :communication, :debugging, presence: true,
            numericality: { greater_than_or_equal_to: 0 }
end

trim/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

trim/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      # Deliver the signup email
      UserMailer.send_apprentice_email(@user).deliver
      redirect_to(@user, :notice => 'Your profile was created!')
    else
      render :action => 'new'
    end

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fullname, :email, :repo, :url, :oop, :modular, :workflow, :testing, :database, :problem, :energy, :intelligence, :javascript, :html, :css, :team, :selfmotivate, :communication, :debugging)
    end
end

trim/app/helpers/application_helper.rb
module ApplicationHelper
end

trim/app/helpers/users_helper.rb
module UsersHelper
end

trim/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trim</title>
  <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

trim/app/views/users/_form.html.erb
    <div class="col-md-8 col-sm-8 col-xs-8 col-xs-offset-2 col-md-offset-2 col-sm-offset-2 form-border">

        <%= form_for(@user) do |f| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="col-md-12 col-sm-12 col-xs-12 form-group">
            <%= f.text_field :fullname, placeholder: "  F U L L  N A M E", class:"inputbox"%>
          </div>

          <div class="col-md-12 col-sm-12 col-xs-12 form-group">
            <%= f.text_field :email, placeholder: "  E M A I L", class:"inputbox" %>
          </div>

          <div class="col-md-12 col-sm-12 col-xs-12 form-group">
            <%= f.text_field :repo, placeholder: "  P R O J E C T  R E P O", class:"inputbox" %>
          </div>

          <div class="col-md-12 col-sm-12 col-xs-12 form-group">
            <%= f.text_field :url, placeholder: "  P R O J E C T  U R L", class:"inputbox" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">USING   BEST   PRACTICES  FOR  OOP :</p>
            <%= f.number_field :oop, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"oop" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">MODULAR DEVELOPMENT: </p>
            <%= f.number_field :modular, class:"inputbox-small col-md-2 col-sm-2 col-xs-2 ", id:"modular" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">FULL STACK WORKFLOW UNDERSTANDING: </p>
            <%= f.number_field :workflow, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"workflow"  %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">TESTING: </p>
            <%= f.number_field :testing, class:"inputbox-small col-md-2 col-sm-2 col-xs-2 col-xs-2", id:"testing" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">DATABASE KNOWLEDGE: </p>
            <%= f.number_field :database, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"database" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">PROBLEM SOLVING SKILLS: </p>
            <%= f.number_field :problem, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"problem" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">JAVASCRIPT: </p>
            <%= f.number_field :javascript, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"javascript" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">HTML: </p>
            <%= f.number_field :html, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"html" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">CSS: </p>
            <%= f.number_field :css, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"css" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">WORKING ON A TEAM: </p>
            <%= f.number_field :team, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"team" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">SELF MOTIVATION: </p>
            <%= f.number_field :selfmotivate, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"selfmotivate" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">COMMUNICATION SKILLS: </p>
            <%= f.number_field :communication, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"communication" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">DEBUGGING: </p>
            <%= f.number_field :debugging, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"debugging" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">YOUR ENERGY LEVEL: </p>
            <%= f.number_field :energy, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"energy" %>
          </div>

          <div class="form-group">
            <p class="form-label col-md-10 col-sm-8 col-xs-8 label-text">INTELLIGENCE: </p>
            <%= f.number_field :intelligence, class:"inputbox-small col-md-2 col-sm-2 col-xs-2", id:"intelligence" %>
          </div>

          <div class="col-md-12 col-sm-12 col-xs-12  form-group">
            <%= f.submit "S U B M I T", class:"inputbox", id:"submitbox" %>
          </div>

      </div>
    </div>


        <% end %>

trim/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container text-center">
  <h1 class="landing"> So you think your good enough to join Trim Agency?</h1>
  <h1 class="landing">Prove it! Click the picture below!</h1>
</div>

<div class="container text-center">
  <%= link_to (image_tag('gp.jpg')), apprentice_path %>
</div>

trim/app/views/users/new.html.erb
<div class="container text-center">
  <h1 class="form-header">Your first step to greatness!</h1>
  <h2 class="form-header lead">Instructions: You only have 50 points to rate yourself in 13 categories.  Spend your points wisely!</h2>
  <h2 class="form-header">When finished click the submit button.<h2>
</div>

<div class="container">
  <%= render 'form' %>
</div>

trim/app/views/users/show.html.erb
<div class="container text-center landing">
  <h1>Your user profile was successfully created. We will be in touch.</h1>
</div>

<div class="container landing">
  <h3>INFO:</h3>
  <div>
    <p>Fullname:</p>
    <%=@user.fullname %>
  </div>

  <br>

  <div>
    <p>Email:</p>
    <%= @user.email %>
  </div>

  <br>

  <div>
    <p>Project Repo:</p>
    <%= @user.repo %>
  </div>

  <br>

  <div>
    <p>Project Url:</p>
    <%= @user.url %>
  </div>
  <hr>

  <h3>Points:</h3>
  <div>
    <p>Using Best Practices For OOP: <%= @user.oop %></p>
  </div>

  <div>
    <p>Modular Development: <%= @user.modular %></p>
  </div>

  <div>
    <p>Full Stack Workflow Understanding: <%= @user.workflow %></p>
  </div>

  <div>
    <p>Testing: <%= @user.testing %></p>
  </div>

  <div>
    <p>Database Knowledge: <%= @user.database %></p>
  </div>

  <div>
    <p>Problem Solving Skills: <%= @user.problem %></p>
  </div>

  <div>
    <p>Javascript: <%= @user.javascript %></p>
  </div>

  <div>
    <p>HTML: <%= @user.html %></p>
  </div>

  <div>
    <p>CSS: <%= @user.css %></p>
  </div>

  <div>
    <p>Working on a Team: <%= @user.team %></p>
  </div>

  <div>
    <p>Self Motivation: <%= @user.selfmotivate %></p>
  </div>

  <div>
    <p>Communication Skills: <%= @user.communication %></p>
  </div>

  <div>
    <p>Debuggin: <%= @user.debugging %></p>
  </div>

  <div>
    <p>Your energy level: <%= @user.energy %></p>
  </div>

  <div>
    <p>intelligence: <%= @user.intelligence %></p>
  </div>

  <div class="text-right">
    <h3><%= link_to 'Back', welcome_path %></h3>
  </div>

</div>